# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcd',
            name='modId',
            field=models.ForeignKey(db_column='mod_id', on_delete=django.db.models.deletion.CASCADE, related_name='r_com_cd_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID'),
        ),
        migrations.AddField(
            model_name='comcd',
            name='regId',
            field=models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_com_cd_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID'),
        ),
    ]
