# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_auto_20170727_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComHttpStatus',
            fields=[
                ('status', models.CharField(db_column='status', max_length=8, primary_key=True, serialize=False, verbose_name='Http 상태코드')),
                ('title', models.CharField(db_column='title', max_length=100, verbose_name='타이틀')),
                ('message', models.CharField(db_column='message', default=None, max_length=500, verbose_name='메세지')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_common_comhttpstatus_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_common_comhttpstatus_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'com_http_status',
            },
        ),
    ]
