# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20170731_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcd',
            name='srtCd',
            field=models.CharField(blank=True, db_column='srt_cd', default=None, max_length=3, null=True, verbose_name='단축코드'),
        ),
    ]
