# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_comcd_srtcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcd',
            name='cdCss',
            field=models.CharField(blank=True, db_column='cd_css', max_length=200, null=True, verbose_name='코드CSS'),
        ),
    ]
