# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_comcd_cdcss'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comcd',
            unique_together=set([('grpCd', 'srtCd')]),
        ),
    ]
