# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userId', models.CharField(db_column='user_id', default=None, max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('userNm', models.CharField(db_column='user_nm', default=None, max_length=30, verbose_name='사용자 이름')),
                ('email', models.EmailField(db_column='email', default=None, max_length=255, unique=True, verbose_name='이메일')),
                ('telNo', models.CharField(db_column='tel_no', default=None, max_length=20, verbose_name='전화')),
                ('cellNo', models.CharField(blank=True, db_column='cell_no', default=None, max_length=20, verbose_name='휴대폰')),
                ('zipCd', models.CharField(blank=True, db_column='zip_cd', default=None, max_length=7, verbose_name='우편번호')),
                ('addr1', models.TextField(blank=True, db_column='addr1', default=None, max_length=200, verbose_name='주소1')),
                ('addr2', models.TextField(blank=True, db_column='addr2', default=None, max_length=200, verbose_name='주소2')),
                ('userAuth', models.CharField(blank=True, db_column='user_auth', default=None, max_length=1, verbose_name='사용자권한')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_user_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_user_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='SysCompany',
            fields=[
                ('companyId', models.CharField(db_column='company_id', default=None, max_length=8, primary_key=True, serialize=False, verbose_name='회사ID')),
                ('companyNm', models.CharField(blank=True, db_column='company_nm', max_length=100, verbose_name='회사명')),
                ('companyTp', models.CharField(blank=True, db_column='company_tp', default=None, max_length=1, verbose_name='회사구분')),
                ('companyGrade', models.CharField(blank=True, db_column='company_grade', default='A', max_length=1, verbose_name='회사등급')),
                ('telNo', models.CharField(blank=True, db_column='tel_no', max_length=16, verbose_name='회사전화번호')),
                ('cellNo', models.CharField(blank=True, db_column='cell_no', max_length=16, verbose_name='회사전화번호(대표)')),
                ('zipCd', models.CharField(blank=True, db_column='zip_cd', max_length=6, verbose_name='회사우편번호')),
                ('addr1', models.TextField(blank=True, db_column='addr_1', max_length=200, verbose_name='회사기본주소')),
                ('addr2', models.TextField(blank=True, db_column='addr_2', max_length=200, verbose_name='회사상세주소')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_company_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_company_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_company',
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('menuId', models.CharField(blank=True, db_column='menu_id', max_length=10, primary_key=True, serialize=False, verbose_name='메뉴ID')),
                ('menuNm', models.CharField(blank=True, db_column='menu_nm', max_length=100, null=True, verbose_name='메뉴명')),
                ('menuUrl', models.CharField(db_column='menu_url', max_length=256, verbose_name='메뉴링크')),
                ('menuLvl', models.IntegerField(db_column='menu_lvl', default=1, verbose_name='메뉴레벨')),
                ('menuCss', models.CharField(blank=True, db_column='menu_css', max_length=200, null=True, verbose_name='메뉴CSS')),
                ('menuDesc', models.CharField(blank=True, db_column='menu_desc', default='', max_length=200, verbose_name='메뉴설명')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
                ('upMenuId', models.ForeignKey(blank=True, db_column='up_menu_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_up_menu_id', to='system.SysMenu', verbose_name='상위메뉴ID')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysMenuAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('menuAuth', models.ForeignKey(db_column='menu_auth', on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_auth_menu_auth', to='common.ComCd', verbose_name='메뉴권한')),
                ('menuId', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_auth_menu_id', to='system.SysMenu', verbose_name='메뉴ID')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_auth_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_auth_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_menu_auth',
            },
        ),
        migrations.CreateModel(
            name='SysMenuCompanyTp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('companyTp', models.ForeignKey(db_column='company_tp', on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_company_tp_company_tp', to='common.ComCd', verbose_name='메뉴회사타입')),
                ('menuId', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_company_tp_menu_id', to='system.SysMenu', verbose_name='메뉴ID')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_company_tp_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_menu_company_tp_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_menu_company_tp',
            },
        ),
        migrations.CreateModel(
            name='SysShop',
            fields=[
                ('shopId', models.CharField(db_column='shop_id', default=None, max_length=8, primary_key=True, serialize=False, verbose_name='매장ID')),
                ('shopNm', models.CharField(blank=True, db_column='shop_nm', max_length=100, verbose_name='매장명')),
                ('telNo', models.CharField(blank=True, db_column='tel_no', max_length=16, verbose_name='매장전화번호')),
                ('cellNo', models.CharField(blank=True, db_column='cell_no', max_length=16, verbose_name='매장휴대폰번호')),
                ('zipCd', models.CharField(blank=True, db_column='zip_cd', max_length=6, verbose_name='매장우편번호')),
                ('addr1', models.TextField(blank=True, db_column='addr_1', max_length=200, verbose_name='매장기본주소')),
                ('addr2', models.TextField(blank=True, db_column='addr_2', max_length=200, verbose_name='매장상세주소')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('companyId', models.ForeignKey(blank=True, db_column='company_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_shop_company_id', to='system.SysCompany')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_shop_tp_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_shop_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_shop',
            },
        ),
        migrations.AddField(
            model_name='sysuser',
            name='shopId',
            field=models.ForeignKey(blank=True, db_column='shop_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_user_shop_id', to='system.SysShop'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='sysmenucompanytp',
            unique_together=set([('menuId', 'companyTp')]),
        ),
        migrations.AlterUniqueTogether(
            name='sysmenuauth',
            unique_together=set([('menuId', 'menuAuth')]),
        ),
    ]
