# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syscompany',
            name='companyGrade',
            field=models.ForeignKey(blank=True, db_column='company_grade', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_company_company_grade', to='common.ComCd', verbose_name='회사등급'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='companyTp',
            field=models.ForeignKey(blank=True, db_column='company_tp', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_company_company_tp', to='common.ComCd', verbose_name='회사구분'),
        ),
    ]
