# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20170716_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='addr1',
            field=models.TextField(blank=True, db_column='addr1', default=None, max_length=200, null=True, verbose_name='주소1'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='addr2',
            field=models.TextField(blank=True, db_column='addr2', default=None, max_length=200, null=True, verbose_name='주소2'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='cellNo',
            field=models.CharField(blank=True, db_column='cell_no', default=None, max_length=20, null=True, verbose_name='휴대폰'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='email',
            field=models.EmailField(blank=True, db_column='email', default=None, max_length=255, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='shopId',
            field=models.ForeignKey(blank=True, db_column='shop_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_user_shop_id', to='system.SysShop', verbose_name='매장ID'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='telNo',
            field=models.CharField(blank=True, db_column='tel_no', default=None, max_length=20, null=True, verbose_name='전화'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='userAuth',
            field=models.ForeignKey(blank=True, db_column='user_auth', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sys_user_user_auth', to='common.ComCd', verbose_name='사용자권한'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='userId',
            field=models.CharField(db_column='user_id', max_length=16, primary_key=True, serialize=False, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='userNm',
            field=models.CharField(db_column='user_nm', max_length=30, verbose_name='사용자 이름'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='zipCd',
            field=models.CharField(blank=True, db_column='zip_cd', default=None, max_length=7, null=True, verbose_name='우편번호'),
        ),
    ]
