# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20170717_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysmenu',
            name='menuCompanyTp',
        ),
    ]
