# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20170717_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysmenu',
            name='menuUrl',
        ),
        migrations.AddField(
            model_name='sysmenu',
            name='menuTmp',
            field=models.CharField(blank=True, db_column='menu_tmp', default=None, max_length=512, null=True, verbose_name='메뉴템플릿'),
        ),
    ]
