# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170727_1949'),
        ('system', '0008_syspolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysMsg',
            fields=[
                ('msgCd', models.CharField(db_column='msg_cd', max_length=6, primary_key=True, serialize=False, verbose_name='메세지코드')),
                ('title', models.CharField(db_column='title', default=None, max_length=100, verbose_name='메세지제목')),
                ('msg', models.CharField(db_column='msg', default=None, max_length=500, verbose_name='메세지내용')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysmsg_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('msgTp', models.ForeignKey(blank=True, db_column='msg_tp', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysmsg_msg_tp', to='common.ComCd', verbose_name='메세지타입')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysmsg_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_msg',
            },
        ),
    ]
