# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20170727_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='cellNo',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='telNo',
        ),
        migrations.AddField(
            model_name='sysuser',
            name='cellNo1',
            field=models.CharField(blank=True, db_column='cell_no1', default=None, max_length=5, null=True, verbose_name='휴대폰1'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='cellNo2',
            field=models.CharField(blank=True, db_column='cell_no2', default=None, max_length=5, null=True, verbose_name='휴대폰2'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='cellNo3',
            field=models.CharField(blank=True, db_column='cell_no3', default=None, max_length=5, null=True, verbose_name='휴대폰3'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='telNo1',
            field=models.CharField(blank=True, db_column='tel_no1', default=None, max_length=5, null=True, verbose_name='전화1'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='telNo2',
            field=models.CharField(blank=True, db_column='tel_no2', default=None, max_length=5, null=True, verbose_name='전화2'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='telNo3',
            field=models.CharField(blank=True, db_column='tel_no3', default=None, max_length=5, null=True, verbose_name='전화3'),
        ),
    ]
