# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20170728_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syscompany',
            name='cellNo',
        ),
        migrations.RemoveField(
            model_name='syscompany',
            name='telNo',
        ),
        migrations.RemoveField(
            model_name='sysshop',
            name='cellNo',
        ),
        migrations.RemoveField(
            model_name='sysshop',
            name='telNo',
        ),
        migrations.AddField(
            model_name='syscompany',
            name='cellNo1',
            field=models.CharField(blank=True, db_column='cell_no1', default=None, max_length=5, null=True, verbose_name='회사휴대폰1'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='cellNo2',
            field=models.CharField(blank=True, db_column='cell_no2', default=None, max_length=5, null=True, verbose_name='회사휴대폰2'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='cellNo3',
            field=models.CharField(blank=True, db_column='cell_no3', default=None, max_length=5, null=True, verbose_name='회사휴대폰3'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='telNo1',
            field=models.CharField(blank=True, db_column='tel_no1', default=None, max_length=5, null=True, verbose_name='회사전화1'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='telNo2',
            field=models.CharField(blank=True, db_column='tel_no2', default=None, max_length=5, null=True, verbose_name='회사전화2'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='telNo3',
            field=models.CharField(blank=True, db_column='tel_no3', default=None, max_length=5, null=True, verbose_name='회사전화3'),
        ),
        migrations.AddField(
            model_name='sysshop',
            name='cellNo1',
            field=models.CharField(blank=True, db_column='cell_no1', default=None, max_length=5, null=True, verbose_name='매장휴대폰1'),
        ),
        migrations.AddField(
            model_name='sysshop',
            name='cellNo2',
            field=models.CharField(blank=True, db_column='cell_no2', default=None, max_length=5, null=True, verbose_name='매장휴대폰2'),
        ),
        migrations.AddField(
            model_name='sysshop',
            name='cellNo3',
            field=models.CharField(blank=True, db_column='cell_no3', default=None, max_length=5, null=True, verbose_name='매장휴대폰3'),
        ),
        migrations.AddField(
            model_name='sysshop',
            name='telNo1',
            field=models.CharField(blank=True, db_column='tel_no1', default=None, max_length=5, null=True, verbose_name='매장전화1'),
        ),
        migrations.AddField(
            model_name='sysshop',
            name='telNo2',
            field=models.CharField(blank=True, db_column='tel_no2', default=None, max_length=5, null=True, verbose_name='매장전화2'),
        ),
        migrations.AddField(
            model_name='sysshop',
            name='telNo3',
            field=models.CharField(blank=True, db_column='tel_no3', default=None, max_length=5, null=True, verbose_name='매장전화3'),
        ),
    ]
