# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170727_1949'),
        ('system', '0012_auto_20170728_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysAppReq',
            fields=[
                ('reqId', models.CharField(db_column='req_id', default=None, max_length=8, primary_key=True, serialize=False, verbose_name='회사ID')),
                ('companyNm', models.CharField(blank=True, db_column='company_nm', max_length=100, verbose_name='회사명')),
                ('shopNm', models.CharField(blank=True, db_column='shop_nm', max_length=100, verbose_name='대표매장명')),
                ('bizLicNo1', models.CharField(blank=True, db_column='biz_lic_no1', max_length=3, null=True, verbose_name='사업자번호1')),
                ('bizLicNo2', models.CharField(blank=True, db_column='biz_lic_no2', max_length=2, null=True, verbose_name='사업자번호2')),
                ('bizLicNo3', models.CharField(blank=True, db_column='biz_lic_no3', max_length=5, null=True, verbose_name='사업자번호3')),
                ('telNo1', models.CharField(blank=True, db_column='tel_no1', default=None, max_length=5, null=True, verbose_name='회사전화1')),
                ('telNo2', models.CharField(blank=True, db_column='tel_no2', default=None, max_length=5, null=True, verbose_name='회사전화2')),
                ('telNo3', models.CharField(blank=True, db_column='tel_no3', default=None, max_length=5, null=True, verbose_name='회사전화3')),
                ('cellNo1', models.CharField(blank=True, db_column='cell_no1', default=None, max_length=5, null=True, verbose_name='회사휴대폰1')),
                ('cellNo2', models.CharField(blank=True, db_column='cell_no2', default=None, max_length=5, null=True, verbose_name='회사휴대폰2')),
                ('cellNo3', models.CharField(blank=True, db_column='cell_no3', default=None, max_length=5, null=True, verbose_name='회사휴대폰3')),
                ('bizTp', models.CharField(blank=True, db_column='biz_tp', max_length=100, null=True, verbose_name='업태')),
                ('bizKind', models.CharField(blank=True, db_column='biz_kind', max_length=100, null=True, verbose_name='업종')),
                ('zipCd', models.CharField(blank=True, db_column='zip_cd', max_length=6, verbose_name='회사우편번호')),
                ('addr1', models.TextField(blank=True, db_column='addr_1', max_length=200, verbose_name='회사기본주소')),
                ('addr2', models.TextField(blank=True, db_column='addr_2', max_length=200, verbose_name='회사상세주소')),
                ('userId', models.CharField(db_column='user_id', max_length=16, verbose_name='대표사용자아이디')),
                ('password', models.CharField(db_column='password', max_length=128, verbose_name='대표사용자비밀번호')),
                ('email', models.EmailField(blank=True, db_column='email', default=None, max_length=255, null=True, verbose_name='이메일')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('companyGrade', models.ForeignKey(blank=True, db_column='company_grade', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysappreq_company_grade', to='common.ComCd', verbose_name='회사등급')),
                ('companyTp', models.ForeignKey(blank=True, db_column='company_tp', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysappreq_company_tp', to='common.ComCd', verbose_name='회사구분')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysappreq_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysappreq_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_app_req',
            },
        ),
        migrations.AddField(
            model_name='syscompany',
            name='bizKind',
            field=models.CharField(blank=True, db_column='biz_kind', max_length=100, null=True, verbose_name='업종'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='bizLicNo1',
            field=models.CharField(blank=True, db_column='biz_lic_no1', max_length=3, null=True, verbose_name='사업자번호1'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='bizLicNo2',
            field=models.CharField(blank=True, db_column='biz_lic_no2', max_length=2, null=True, verbose_name='사업자번호2'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='bizLicNo3',
            field=models.CharField(blank=True, db_column='biz_lic_no3', max_length=5, null=True, verbose_name='사업자번호3'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='bizTp',
            field=models.CharField(blank=True, db_column='biz_tp', max_length=100, null=True, verbose_name='업태'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='addr1',
            field=models.TextField(blank=True, db_column='addr_1', max_length=200, null=True, verbose_name='회사기본주소'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='addr2',
            field=models.TextField(blank=True, db_column='addr_2', max_length=200, null=True, verbose_name='회사상세주소'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='zipCd',
            field=models.CharField(blank=True, db_column='zip_cd', max_length=6, null=True, verbose_name='회사우편번호'),
        ),
    ]
