# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20170728_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysappreq',
            name='companyCd',
            field=models.ForeignKey(blank=True, db_column='company_cd', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysappreq_company_cd', to='system.SysCompany', verbose_name='회사코드'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='userId',
            field=models.CharField(db_column='user_id', max_length=20, primary_key=True, serialize=False, verbose_name='아이디'),
        ),
    ]
