# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_sysseq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysseq',
            name='id',
        ),
        migrations.AddField(
            model_name='sysseq',
            name='seq',
            field=models.IntegerField(db_column='seq', default=0, verbose_name='ID-순차번호'),
        ),
    ]
