# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20170801_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysshop',
            name='shopId',
            field=models.CharField(db_column='shop_id', default=None, max_length=10, primary_key=True, serialize=False, verbose_name='매장ID'),
        ),
    ]
