# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20170801_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='syscompany',
            name='isReal',
            field=models.BooleanField(db_column='is_real', default=True, verbose_name='실회사구분'),
        ),
    ]
