# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_syscompany_isreal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysseq',
            name='seqLen',
            field=models.IntegerField(db_column='seq_len', default=10, verbose_name='SEQ 길이'),
        ),
        migrations.AddField(
            model_name='sysseq',
            name='seqPrefix',
            field=models.CharField(blank=True, db_column='seq_prefix', default=None, max_length=3, null=True, verbose_name='SEQ Prefix'),
        ),
    ]
