# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_auto_20170802_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysseq',
            name='isYm',
            field=models.BooleanField(db_column='isYm', default=False, verbose_name='SEQ 년월추가여부'),
        ),
    ]
