# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_sysseq_isym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysappreq',
            name='reqId',
            field=models.CharField(db_column='req_id', default=None, max_length=10, primary_key=True, serialize=False, verbose_name='회사ID'),
        ),
    ]
