# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20170802_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='syscompany',
            name='policyId',
            field=models.ForeignKey(blank=True, db_column='policy_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_syscompany_policy_id', to='system.SysPolicy', verbose_name='이용약관ID'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='shopNm',
            field=models.CharField(db_column='shop_nm', max_length=100, verbose_name='대표매장명'),
        ),
    ]
