# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_auto_20170803_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysappreq',
            name='policyId',
            field=models.ForeignKey(blank=True, db_column='policy_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysappreq_policy_id', to='system.SysPolicy', verbose_name='이용약관ID'),
        ),
    ]
