# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_sysappreq_policyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysseq',
            name='isYm',
        ),
        migrations.AddField(
            model_name='sysseq',
            name='useYm',
            field=models.BooleanField(db_column='use_ym', default=False, verbose_name='SEQ 년월사용여부'),
        ),
    ]
