# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_auto_20170803_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sysappreq',
            unique_together=set([('userId',)]),
        ),
    ]
