# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_auto_20170803_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysappreq',
            name='companyNm',
            field=models.CharField(db_column='company_nm', max_length=100, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='policyId',
            field=models.ForeignKey(db_column='policy_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysappreq_policy_id', to='system.SysPolicy', verbose_name='이용약관ID'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='reqId',
            field=models.CharField(db_column='req_id', max_length=10, primary_key=True, serialize=False, verbose_name='요청ID'),
        ),
    ]
