# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_auto_20170804_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysappreq',
            name='userNm',
            field=models.CharField(db_column='user_nm', default=None, max_length=30, verbose_name='대표사용자명'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='userId',
            field=models.CharField(db_column='user_id', default=None, max_length=20, verbose_name='대표사용자아이디'),
        ),
    ]
