# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_auto_20170807_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysappreq',
            name='cellNo1',
            field=models.CharField(db_column='cell_no1', default=None, max_length=5, verbose_name='대표자휴대폰1'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='cellNo2',
            field=models.CharField(db_column='cell_no2', default=None, max_length=5, verbose_name='대표자휴대폰2'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='cellNo3',
            field=models.CharField(db_column='cell_no3', default=None, max_length=5, verbose_name='대표자휴대폰3'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='telNo1',
            field=models.CharField(blank=True, db_column='tel_no1', default=None, max_length=5, null=True, verbose_name='회사전화1'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='telNo2',
            field=models.CharField(blank=True, db_column='tel_no2', default=None, max_length=5, null=True, verbose_name='회사전화2'),
        ),
        migrations.AlterField(
            model_name='sysappreq',
            name='telNo3',
            field=models.CharField(blank=True, db_column='tel_no3', default=None, max_length=5, null=True, verbose_name='회사전화3'),
        ),
    ]
