# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_auto_20170807_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysappreq',
            name='reqStatus',
            field=models.CharField(db_column='req_status', default='00', max_length=2, verbose_name='진행상태'),
        ),
    ]
