# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_sysappreq_reqstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysappreq',
            name='reqDt',
            field=models.DateTimeField(auto_now_add=True, db_column='req_dt', null=True, verbose_name='요청일자'),
        ),
    ]
