# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0038_auto_20170809_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysappreq',
            name='reqStatus',
            field=models.CharField(blank=True, db_column='req_status', default=None, max_length=8, null=True, verbose_name='진행상태'),
        ),
    ]
