# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0044_auto_20170809_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syscompany',
            name='isReal',
            field=models.BooleanField(db_column='is_real', default=False, verbose_name='실회사구분'),
        ),
    ]
