# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0045_auto_20170810_2104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sysappreq',
            table='sys_appreq',
        ),
    ]
