# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0046_auto_20170811_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysappreq',
            name='appDt',
            field=models.DateTimeField(blank=True, db_column='app_dt', null=True, verbose_name='승인일자'),
        ),
    ]
