# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0052_sysshop_ismain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='loginCnt',
            field=models.IntegerField(db_column='login_cnt', default=0, verbose_name='로그인회수'),
        ),
    ]
