# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0053_sysuser_logincnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginDt', models.DateTimeField(auto_now_add=True, db_column='login_dt', verbose_name='로그인일자')),
                ('httpUserAgent', models.TextField(blank=True, db_column='http_user_agent', default=None, null=True, verbose_name='UserAgent정보')),
                ('remoteAddr', models.TextField(blank=True, db_column='remote_addr', default=None, null=True, verbose_name='접속 IP')),
                ('remoteHost', models.TextField(blank=True, db_column='remote_host', default=None, null=True, verbose_name='접속 Host')),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysloginhistory_user_id', to=settings.AUTH_USER_MODEL, verbose_name='사용자ID')),
            ],
            options={
                'db_table': 'sys_login_history',
            },
        ),
    ]
