# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0055_auto_20170903_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysappreq',
            name='faxNo1',
            field=models.CharField(blank=True, db_column='fax_no1', default=None, max_length=5, null=True, verbose_name='회사FAX1'),
        ),
        migrations.AddField(
            model_name='sysappreq',
            name='faxNo2',
            field=models.CharField(blank=True, db_column='fax_no2', default=None, max_length=5, null=True, verbose_name='회사FAX2'),
        ),
        migrations.AddField(
            model_name='sysappreq',
            name='faxNo3',
            field=models.CharField(blank=True, db_column='fax_no3', default=None, max_length=5, null=True, verbose_name='회사FAX3'),
        ),
    ]
