# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0056_auto_20170904_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysshop',
            name='shopId',
            field=models.CharField(db_column='shop_id', default=None, max_length=14, primary_key=True, serialize=False, verbose_name='매장ID'),
        ),
    ]
