# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0057_auto_20170904_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='syscompany',
            name='chargerNm',
            field=models.CharField(blank=True, db_column='charger_nm', max_length=30, null=True, verbose_name='담당자 이름'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='cellNo1',
            field=models.CharField(blank=True, db_column='cell_no1', default=None, max_length=5, null=True, verbose_name='담당자휴대폰1'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='cellNo2',
            field=models.CharField(blank=True, db_column='cell_no2', default=None, max_length=5, null=True, verbose_name='담당자휴대폰2'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='cellNo3',
            field=models.CharField(blank=True, db_column='cell_no3', default=None, max_length=5, null=True, verbose_name='담당자휴대폰3'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='isReal',
            field=models.BooleanField(db_column='is_real', default=False, verbose_name='실제회사구분'),
        ),
    ]
