# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0058_auto_20170904_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysCompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('accountId', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='r_system_syscompanyaccount_account_id', to='system.SysCompany', verbose_name='거래처ID')),
                ('companyId', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='r_system_syscompanyaccount_company_id', to='system.SysCompany', verbose_name='회사ID')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_syscompanyaccount_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_syscompanyaccount_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_company_account',
            },
        ),
        migrations.AlterUniqueTogether(
            name='syscompanyaccount',
            unique_together=set([('companyId', 'accountId')]),
        ),
    ]
