# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0059_auto_20170904_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='syscompanyaccount',
            name='telecomId',
            field=models.TextField(blank=True, db_column='telecom_id', max_length=200, null=True, verbose_name='통신사ID'),
        ),
    ]
