# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0061_syscompany_telecomcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syscompanyaccount',
            name='telecomId',
        ),
    ]
