# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0063_sysappreq_telecomcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syscompany',
            name='companyNm',
            field=models.CharField(db_column='company_nm', max_length=100, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='syscompany',
            name='companyTp',
            field=models.ForeignKey(db_column='company_tp', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_syscompany_company_tp', to='common.ComCd', verbose_name='회사구분'),
        ),
    ]
