# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0064_auto_20170906_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysNetwork',
            fields=[
                ('networkCd', models.CharField(db_column='network_cd', max_length=2, primary_key=True, serialize=False, verbose_name='통신망 코드')),
                ('networkNm', models.CharField(blank=True, db_column='network_nm', max_length=100, null=True, verbose_name='통신망 명')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysnetwork_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysnetwork_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_network',
            },
        ),
        migrations.CreateModel(
            name='SysNetworkTelecom',
            fields=[
                ('networkTelecomCd', models.CharField(db_column='network_telecom_cd', max_length=6, primary_key=True, serialize=False, verbose_name='통신망 통신사 코드')),
                ('isMvno', models.BooleanField(db_column='is_mvno', default=False, verbose_name='MVNO구분')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysnetworktelecom_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('networkCd', models.ForeignKey(db_column='network_cd', on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysnetworktelecom_network_cd', to='system.SysNetwork', verbose_name='통신망코드')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysnetworktelecom_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_network_telecom',
            },
        ),
        migrations.CreateModel(
            name='SysTelecom',
            fields=[
                ('telecomCd', models.CharField(db_column='telecom_cd', max_length=2, primary_key=True, serialize=False, verbose_name='통신사 코드')),
                ('telecomNm', models.CharField(blank=True, db_column='telecom_nm', max_length=100, null=True, verbose_name='통신사 명')),
                ('isMvno', models.BooleanField(db_column='is_mvno', default=False, verbose_name='MVNO구분')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('modId', models.ForeignKey(blank=True, db_column='mod_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_systelecom_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_system_systelecom_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
            ],
            options={
                'db_table': 'sys_telecom',
            },
        ),
        migrations.AddField(
            model_name='sysnetworktelecom',
            name='telecomCd',
            field=models.ForeignKey(db_column='telecom_cd', on_delete=django.db.models.deletion.CASCADE, related_name='r_system_sysnetworktelecom_telecom_cd', to='system.SysTelecom', verbose_name='통신사코드'),
        ),
    ]
