# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0066_auto_20170908_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysnetworktelecom',
            name='isMvno',
        ),
        migrations.AddField(
            model_name='sysnetworktelecom',
            name='networkTelecomNm',
            field=models.CharField(blank=True, db_column='network_telecom_nm', max_length=100, null=True, verbose_name='망통신사 명'),
        ),
    ]
