# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0068_auto_20170908_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysappreq',
            name='telecomCd',
        ),
        migrations.RemoveField(
            model_name='syscompany',
            name='telecomCd',
        ),
        migrations.AddField(
            model_name='sysappreq',
            name='networkTelecomCd',
            field=models.CharField(blank=True, db_column='network_Telecom_cd', default=None, max_length=200, null=True, verbose_name='통신사코드'),
        ),
        migrations.AddField(
            model_name='syscompany',
            name='networkTelecomCd',
            field=models.CharField(blank=True, db_column='network_telecom_cd', default=None, max_length=200, null=True, verbose_name='통신사코드'),
        ),
    ]
