# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0045_auto_20170810_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProdPhone',
            fields=[
                ('prodId', models.CharField(db_column='prod_id', max_length=14, primary_key=True, serialize=False, verbose_name='상품ID')),
                ('serialNo', models.CharField(db_column='user_id', max_length=30, verbose_name='상품Serial번호')),
                ('modelNm', models.CharField(db_column='model_nm', default=None, max_length=20, verbose_name='모델명')),
                ('prodInfo', models.CharField(db_column='prod_info', default=None, max_length=20, verbose_name='제품정보')),
                ('prodColor', models.CharField(db_column='prod_color', default=None, max_length=20, verbose_name='제품색상')),
                ('inDt', models.DateTimeField(auto_now_add=True, db_column='in_dt', null=True, verbose_name='입고일자')),
                ('inPrice', models.IntegerField(db_column='in_price', default=0, verbose_name='입고가')),
                ('useYn', models.BooleanField(db_column='use_yn', default=True, verbose_name='사용여부')),
                ('regDt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True, verbose_name='등록일자')),
                ('modDt', models.DateTimeField(auto_now=True, db_column='mod_dt', verbose_name='수정일자')),
                ('inStaffId', models.ForeignKey(blank=True, db_column='in_staff_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_stock_prod_phone_in_staff_id', to=settings.AUTH_USER_MODEL, verbose_name='입고직원ID')),
                ('modId', models.ForeignKey(db_column='mod_id', on_delete=django.db.models.deletion.CASCADE, related_name='r_stock_prod_phone_mod_id', to=settings.AUTH_USER_MODEL, verbose_name='수정자ID')),
                ('regId', models.ForeignKey(blank=True, db_column='reg_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_stock_prod_phone_reg_id', to=settings.AUTH_USER_MODEL, verbose_name='등록자ID')),
                ('shopId', models.ForeignKey(blank=True, db_column='shop_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='r_stock_prod_phone_shop_id', to='system.SysShop', verbose_name='매장ID')),
            ],
            options={
                'db_table': 'stock_prod_phone',
            },
        ),
    ]
